//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The specific combination of an individual Aircraft
 *                 related to a single Flight Leg
 *             
 * 
 * <p>Java class for AircraftForFlightLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AircraftForFlightLeg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="aircraft" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Aircraft"/>
 *         &lt;element name="nextFlightLegForAircraft" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}FlightLegForAircraft" minOccurs="0"/>
 *         &lt;element name="previousFlightLegForAircraft" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}FlightLegForAircraft" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AircraftForFlightLeg", propOrder = {
    "aircraft",
    "nextFlightLegForAircraft",
    "previousFlightLegForAircraft"
})
public class AircraftForFlightLeg {

    @XmlElement(required = true)
    protected Aircraft aircraft;
    protected FlightLegForAircraft nextFlightLegForAircraft;
    protected FlightLegForAircraft previousFlightLegForAircraft;

    /**
     * Gets the value of the aircraft property.
     * 
     * @return
     *     possible object is
     *     {@link Aircraft }
     *     
     */
    public Aircraft getAircraft() {
        return aircraft;
    }

    /**
     * Sets the value of the aircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link Aircraft }
     *     
     */
    public void setAircraft(Aircraft value) {
        this.aircraft = value;
    }

    /**
     * Gets the value of the nextFlightLegForAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link FlightLegForAircraft }
     *     
     */
    public FlightLegForAircraft getNextFlightLegForAircraft() {
        return nextFlightLegForAircraft;
    }

    /**
     * Sets the value of the nextFlightLegForAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightLegForAircraft }
     *     
     */
    public void setNextFlightLegForAircraft(FlightLegForAircraft value) {
        this.nextFlightLegForAircraft = value;
    }

    /**
     * Gets the value of the previousFlightLegForAircraft property.
     * 
     * @return
     *     possible object is
     *     {@link FlightLegForAircraft }
     *     
     */
    public FlightLegForAircraft getPreviousFlightLegForAircraft() {
        return previousFlightLegForAircraft;
    }

    /**
     * Sets the value of the previousFlightLegForAircraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightLegForAircraft }
     *     
     */
    public void setPreviousFlightLegForAircraft(FlightLegForAircraft value) {
        this.previousFlightLegForAircraft = value;
    }

}
