//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.joda.time.DateTime;


/**
 * Where a flight does not depart as planned an
 *                 instance of DatedLegDelay records this.
 *             
 * 
 * <p>Java class for Delay complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Delay">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="delayDuration" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Duration" minOccurs="0"/>
 *         &lt;element name="delayReason" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}DelayReasonEnum" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="nightStopDelay" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="nextDelayInformation" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Delay", propOrder = {
    "delayDuration",
    "delayReason",
    "nightStopDelay",
    "nextDelayInformation"
})
public class Delay {

    protected Duration delayDuration;
    protected List<DelayReasonEnum> delayReason;
    protected Boolean nightStopDelay;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime nextDelayInformation;

    /**
     * Gets the value of the delayDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDelayDuration() {
        return delayDuration;
    }

    /**
     * Sets the value of the delayDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDelayDuration(Duration value) {
        this.delayDuration = value;
    }

    /**
     * Gets the value of the delayReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the delayReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDelayReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DelayReasonEnum }
     * 
     * 
     */
    public List<DelayReasonEnum> getDelayReason() {
        if (delayReason == null) {
            delayReason = new ArrayList<DelayReasonEnum>();
        }
        return this.delayReason;
    }

    /**
     * Gets the value of the nightStopDelay property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNightStopDelay() {
        return nightStopDelay;
    }

    /**
     * Sets the value of the nightStopDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNightStopDelay(Boolean value) {
        this.nightStopDelay = value;
    }

    /**
     * Gets the value of the nextDelayInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getNextDelayInformation() {
        return nextDelayInformation;
    }

    /**
     * Sets the value of the nextDelayInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextDelayInformation(DateTime value) {
        this.nextDelayInformation = value;
    }

}
