//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.joda.time.DateTime;


/**
 * A flight leg is a journey made by an aircraft A
 *                 Flight Leg is not marketed, so the only flight number available
 *                 to
 *                 it is the operating one.
 *             
 * 
 * <p>Java class for FlightLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightLeg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="repeatNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ownershipDisclosure" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="currentOrigin" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Movement"/>
 *         &lt;element name="currentDestination" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Movement"/>
 *         &lt;element name="legTimings" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}FlightTimings"/>
 *         &lt;element name="legStatus" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}LegStatus" minOccurs="0"/>
 *         &lt;element name="disruptionReason" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}CustomerNotification" minOccurs="0"/>
 *         &lt;element name="callToAction" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}CustomerNotification" minOccurs="0"/>
 *         &lt;element name="commentary" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Commentary" minOccurs="0"/>
 *         &lt;element name="marketingFlight" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}MarketingFlightNumber" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="aircraftForFlightLeg" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}AircraftForFlightLeg" minOccurs="0"/>
 *         &lt;element name="scheduleOwner" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Organisation" minOccurs="0"/>
 *         &lt;element name="cabinCrewOwner" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Organisation" minOccurs="0"/>
 *         &lt;element name="flightCrewOwner" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Organisation" minOccurs="0"/>
 *         &lt;element name="serviceType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="1"/>
 *               &lt;pattern value="([A-Z])"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="airborneReturnNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="changeReasonCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="diverted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="rerouted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cancelled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="returnToStand" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="exactMatch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="origin" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Movement" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="destination" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Movement" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="operationalEvent" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}OperationalEvent" maxOccurs="20" minOccurs="0"/>
 *         &lt;element name="legDuration" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Duration" minOccurs="0"/>
 *         &lt;element name="updateDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightLeg", propOrder = {
    "repeatNumber",
    "ownershipDisclosure",
    "currentOrigin",
    "currentDestination",
    "legTimings",
    "legStatus",
    "disruptionReason",
    "callToAction",
    "commentary",
    "marketingFlight",
    "aircraftForFlightLeg",
    "scheduleOwner",
    "cabinCrewOwner",
    "flightCrewOwner",
    "serviceType",
    "airborneReturnNumber",
    "changeReasonCode",
    "diverted",
    "rerouted",
    "cancelled",
    "returnToStand",
    "exactMatch",
    "origin",
    "destination",
    "operationalEvent",
    "legDuration",
    "updateDateTime"
})
public class FlightLeg {

    @XmlElement(required = true)
    protected BigInteger repeatNumber;
    protected String ownershipDisclosure;
    @XmlElement(required = true)
    protected Movement currentOrigin;
    @XmlElement(required = true)
    protected Movement currentDestination;
    @XmlElement(required = true)
    protected FlightTimings legTimings;
    protected LegStatus legStatus;
    protected CustomerNotification disruptionReason;
    protected CustomerNotification callToAction;
    protected Commentary commentary;
    protected List<MarketingFlightNumber> marketingFlight;
    protected AircraftForFlightLeg aircraftForFlightLeg;
    protected Organisation scheduleOwner;
    protected Organisation cabinCrewOwner;
    protected Organisation flightCrewOwner;
    protected String serviceType;
    protected BigInteger airborneReturnNumber;
    protected String changeReasonCode;
    protected Boolean diverted;
    protected Boolean rerouted;
    protected Boolean cancelled;
    protected Boolean returnToStand;
    protected Boolean exactMatch;
    protected List<Movement> origin;
    protected List<Movement> destination;
    protected List<OperationalEvent> operationalEvent;
    protected Duration legDuration;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime updateDateTime;

    /**
     * Gets the value of the repeatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepeatNumber() {
        return repeatNumber;
    }

    /**
     * Sets the value of the repeatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepeatNumber(BigInteger value) {
        this.repeatNumber = value;
    }

    /**
     * Gets the value of the ownershipDisclosure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnershipDisclosure() {
        return ownershipDisclosure;
    }

    /**
     * Sets the value of the ownershipDisclosure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnershipDisclosure(String value) {
        this.ownershipDisclosure = value;
    }

    /**
     * Gets the value of the currentOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Movement }
     *     
     */
    public Movement getCurrentOrigin() {
        return currentOrigin;
    }

    /**
     * Sets the value of the currentOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movement }
     *     
     */
    public void setCurrentOrigin(Movement value) {
        this.currentOrigin = value;
    }

    /**
     * Gets the value of the currentDestination property.
     * 
     * @return
     *     possible object is
     *     {@link Movement }
     *     
     */
    public Movement getCurrentDestination() {
        return currentDestination;
    }

    /**
     * Sets the value of the currentDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movement }
     *     
     */
    public void setCurrentDestination(Movement value) {
        this.currentDestination = value;
    }

    /**
     * Gets the value of the legTimings property.
     * 
     * @return
     *     possible object is
     *     {@link FlightTimings }
     *     
     */
    public FlightTimings getLegTimings() {
        return legTimings;
    }

    /**
     * Sets the value of the legTimings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightTimings }
     *     
     */
    public void setLegTimings(FlightTimings value) {
        this.legTimings = value;
    }

    /**
     * Gets the value of the legStatus property.
     * 
     * @return
     *     possible object is
     *     {@link LegStatus }
     *     
     */
    public LegStatus getLegStatus() {
        return legStatus;
    }

    /**
     * Sets the value of the legStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link LegStatus }
     *     
     */
    public void setLegStatus(LegStatus value) {
        this.legStatus = value;
    }

    /**
     * Gets the value of the disruptionReason property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerNotification }
     *     
     */
    public CustomerNotification getDisruptionReason() {
        return disruptionReason;
    }

    /**
     * Sets the value of the disruptionReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerNotification }
     *     
     */
    public void setDisruptionReason(CustomerNotification value) {
        this.disruptionReason = value;
    }

    /**
     * Gets the value of the callToAction property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerNotification }
     *     
     */
    public CustomerNotification getCallToAction() {
        return callToAction;
    }

    /**
     * Sets the value of the callToAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerNotification }
     *     
     */
    public void setCallToAction(CustomerNotification value) {
        this.callToAction = value;
    }

    /**
     * Gets the value of the commentary property.
     * 
     * @return
     *     possible object is
     *     {@link Commentary }
     *     
     */
    public Commentary getCommentary() {
        return commentary;
    }

    /**
     * Sets the value of the commentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commentary }
     *     
     */
    public void setCommentary(Commentary value) {
        this.commentary = value;
    }

    /**
     * Gets the value of the marketingFlight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketingFlight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketingFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketingFlightNumber }
     * 
     * 
     */
    public List<MarketingFlightNumber> getMarketingFlight() {
        if (marketingFlight == null) {
            marketingFlight = new ArrayList<MarketingFlightNumber>();
        }
        return this.marketingFlight;
    }

    /**
     * Gets the value of the aircraftForFlightLeg property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftForFlightLeg }
     *     
     */
    public AircraftForFlightLeg getAircraftForFlightLeg() {
        return aircraftForFlightLeg;
    }

    /**
     * Sets the value of the aircraftForFlightLeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftForFlightLeg }
     *     
     */
    public void setAircraftForFlightLeg(AircraftForFlightLeg value) {
        this.aircraftForFlightLeg = value;
    }

    /**
     * Gets the value of the scheduleOwner property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getScheduleOwner() {
        return scheduleOwner;
    }

    /**
     * Sets the value of the scheduleOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setScheduleOwner(Organisation value) {
        this.scheduleOwner = value;
    }

    /**
     * Gets the value of the cabinCrewOwner property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getCabinCrewOwner() {
        return cabinCrewOwner;
    }

    /**
     * Sets the value of the cabinCrewOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setCabinCrewOwner(Organisation value) {
        this.cabinCrewOwner = value;
    }

    /**
     * Gets the value of the flightCrewOwner property.
     * 
     * @return
     *     possible object is
     *     {@link Organisation }
     *     
     */
    public Organisation getFlightCrewOwner() {
        return flightCrewOwner;
    }

    /**
     * Sets the value of the flightCrewOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organisation }
     *     
     */
    public void setFlightCrewOwner(Organisation value) {
        this.flightCrewOwner = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceType(String value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the airborneReturnNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAirborneReturnNumber() {
        return airborneReturnNumber;
    }

    /**
     * Sets the value of the airborneReturnNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAirborneReturnNumber(BigInteger value) {
        this.airborneReturnNumber = value;
    }

    /**
     * Gets the value of the changeReasonCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeReasonCode() {
        return changeReasonCode;
    }

    /**
     * Sets the value of the changeReasonCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeReasonCode(String value) {
        this.changeReasonCode = value;
    }

    /**
     * Gets the value of the diverted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDiverted() {
        return diverted;
    }

    /**
     * Sets the value of the diverted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDiverted(Boolean value) {
        this.diverted = value;
    }

    /**
     * Gets the value of the rerouted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRerouted() {
        return rerouted;
    }

    /**
     * Sets the value of the rerouted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRerouted(Boolean value) {
        this.rerouted = value;
    }

    /**
     * Gets the value of the cancelled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCancelled() {
        return cancelled;
    }

    /**
     * Sets the value of the cancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCancelled(Boolean value) {
        this.cancelled = value;
    }

    /**
     * Gets the value of the returnToStand property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnToStand() {
        return returnToStand;
    }

    /**
     * Sets the value of the returnToStand property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnToStand(Boolean value) {
        this.returnToStand = value;
    }

    /**
     * Gets the value of the exactMatch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExactMatch() {
        return exactMatch;
    }

    /**
     * Sets the value of the exactMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExactMatch(Boolean value) {
        this.exactMatch = value;
    }

    /**
     * Gets the value of the origin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Movement }
     * 
     * 
     */
    public List<Movement> getOrigin() {
        if (origin == null) {
            origin = new ArrayList<Movement>();
        }
        return this.origin;
    }

    /**
     * Gets the value of the destination property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destination property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestination().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Movement }
     * 
     * 
     */
    public List<Movement> getDestination() {
        if (destination == null) {
            destination = new ArrayList<Movement>();
        }
        return this.destination;
    }

    /**
     * Gets the value of the operationalEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the operationalEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOperationalEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OperationalEvent }
     * 
     * 
     */
    public List<OperationalEvent> getOperationalEvent() {
        if (operationalEvent == null) {
            operationalEvent = new ArrayList<OperationalEvent>();
        }
        return this.operationalEvent;
    }

    /**
     * Gets the value of the legDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getLegDuration() {
        return legDuration;
    }

    /**
     * Sets the value of the legDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setLegDuration(Duration value) {
        this.legDuration = value;
    }

    /**
     * Gets the value of the updateDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getUpdateDateTime() {
        return updateDateTime;
    }

    /**
     * Sets the value of the updateDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDateTime(DateTime value) {
        this.updateDateTime = value;
    }

}
