//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * The timings of a flight (this may be a whole
 *                 flight, segment or leg) depending on the context of use. It
 *                 covers
 *                 the timings like Scheduled, Estimate and Actual on Departure and
 *                 Arrival.
 *             
 * 
 * <p>Java class for FlightTimings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightTimings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduledDepartureDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="scheduledArrivalDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="estimatedDepartureDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="estimatedArrivalDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="actualDepartureDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="actualArrivalDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightTimings", propOrder = {
    "scheduledDepartureDateTime",
    "scheduledArrivalDateTime",
    "estimatedDepartureDateTime",
    "estimatedArrivalDateTime",
    "actualDepartureDateTime",
    "actualArrivalDateTime"
})
public class FlightTimings {

    protected EventDate scheduledDepartureDateTime;
    protected EventDate scheduledArrivalDateTime;
    protected EventDate estimatedDepartureDateTime;
    protected EventDate estimatedArrivalDateTime;
    protected EventDate actualDepartureDateTime;
    protected EventDate actualArrivalDateTime;

    /**
     * Gets the value of the scheduledDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getScheduledDepartureDateTime() {
        return scheduledDepartureDateTime;
    }

    /**
     * Sets the value of the scheduledDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setScheduledDepartureDateTime(EventDate value) {
        this.scheduledDepartureDateTime = value;
    }

    /**
     * Gets the value of the scheduledArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getScheduledArrivalDateTime() {
        return scheduledArrivalDateTime;
    }

    /**
     * Sets the value of the scheduledArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setScheduledArrivalDateTime(EventDate value) {
        this.scheduledArrivalDateTime = value;
    }

    /**
     * Gets the value of the estimatedDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getEstimatedDepartureDateTime() {
        return estimatedDepartureDateTime;
    }

    /**
     * Sets the value of the estimatedDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setEstimatedDepartureDateTime(EventDate value) {
        this.estimatedDepartureDateTime = value;
    }

    /**
     * Gets the value of the estimatedArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getEstimatedArrivalDateTime() {
        return estimatedArrivalDateTime;
    }

    /**
     * Sets the value of the estimatedArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setEstimatedArrivalDateTime(EventDate value) {
        this.estimatedArrivalDateTime = value;
    }

    /**
     * Gets the value of the actualDepartureDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getActualDepartureDateTime() {
        return actualDepartureDateTime;
    }

    /**
     * Sets the value of the actualDepartureDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setActualDepartureDateTime(EventDate value) {
        this.actualDepartureDateTime = value;
    }

    /**
     * Gets the value of the actualArrivalDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getActualArrivalDateTime() {
        return actualArrivalDateTime;
    }

    /**
     * Sets the value of the actualArrivalDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setActualArrivalDateTime(EventDate value) {
        this.actualArrivalDateTime = value;
    }

}
