//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.joda.time.LocalDate;


/**
 * Individual operation of a consecutive series of
 *                 FlightLegs allocated the same FlightNumber.
 *             
 * 
 * <p>Java class for Flight complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Flight">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operatingFlightNumber" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}OperatingFlightNumber"/>
 *         &lt;element name="originDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="flightLeg" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}FlightLeg" maxOccurs="99"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Flight", propOrder = {
    "operatingFlightNumber",
    "originDate",
    "flightLeg"
})
public class Flight {

    @XmlElement(required = true)
    protected OperatingFlightNumber operatingFlightNumber;
    @XmlElement(required = true, type = String.class)
    @XmlSchemaType(name = "date")
    protected LocalDate originDate;
    @XmlElement(required = true)
    protected List<FlightLeg> flightLeg;

    /**
     * Gets the value of the operatingFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link OperatingFlightNumber }
     *     
     */
    public OperatingFlightNumber getOperatingFlightNumber() {
        return operatingFlightNumber;
    }

    /**
     * Sets the value of the operatingFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatingFlightNumber }
     *     
     */
    public void setOperatingFlightNumber(OperatingFlightNumber value) {
        this.operatingFlightNumber = value;
    }

    /**
     * Gets the value of the originDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public LocalDate getOriginDate() {
        return originDate;
    }

    /**
     * Sets the value of the originDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginDate(LocalDate value) {
        this.originDate = value;
    }

    /**
     * Gets the value of the flightLeg property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flightLeg property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlightLeg().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FlightLeg }
     * 
     * 
     */
    public List<FlightLeg> getFlightLeg() {
        if (flightLeg == null) {
            flightLeg = new ArrayList<FlightLeg>();
        }
        return this.flightLeg;
    }

}
