//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Description of the physical location where
 *                 passengers on a particular Flight Leg will be requested to board
 *                 the
 *                 aircraft.
 *             
 * 
 * <p>Java class for Gate complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Gate">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gateNumber" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gateStatus" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}GateStatusEnum" minOccurs="0"/>
 *         &lt;element name="gateStatusCode" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}GateStatusCodeEnum" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Gate", propOrder = {
    "gateNumber",
    "gateStatus",
    "gateStatusCode"
})
public class Gate {

    protected String gateNumber;
    protected GateStatusEnum gateStatus;
    protected GateStatusCodeEnum gateStatusCode;

    /**
     * Gets the value of the gateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateNumber() {
        return gateNumber;
    }

    /**
     * Sets the value of the gateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateNumber(String value) {
        this.gateNumber = value;
    }

    /**
     * Gets the value of the gateStatus property.
     * 
     * @return
     *     possible object is
     *     {@link GateStatusEnum }
     *     
     */
    public GateStatusEnum getGateStatus() {
        return gateStatus;
    }

    /**
     * Sets the value of the gateStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateStatusEnum }
     *     
     */
    public void setGateStatus(GateStatusEnum value) {
        this.gateStatus = value;
    }

    /**
     * Gets the value of the gateStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link GateStatusCodeEnum }
     *     
     */
    public GateStatusCodeEnum getGateStatusCode() {
        return gateStatusCode;
    }

    /**
     * Sets the value of the gateStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link GateStatusCodeEnum }
     *     
     */
    public void setGateStatusCode(GateStatusCodeEnum value) {
        this.gateStatusCode = value;
    }

}
