//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Response to a search for Flights.
 *                 
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="flight" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Flight" maxOccurs="5000"/>
 *         &lt;element name="BusinessErrors" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}BusinessErrors"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flight",
    "businessErrors"
})
@XmlRootElement(name = "GetAircraftLinkedFlightsResponse")
public class GetAircraftLinkedFlightsResponse {

    protected List<Flight> flight;
    @XmlElement(name = "BusinessErrors")
    protected BusinessErrors businessErrors;

    /**
     * Gets the value of the flight property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flight property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlight().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Flight }
     * 
     * 
     */
    public List<Flight> getFlight() {
        if (flight == null) {
            flight = new ArrayList<Flight>();
        }
        return this.flight;
    }

    /**
     * Gets the value of the businessErrors property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessErrors }
     *     
     */
    public BusinessErrors getBusinessErrors() {
        return businessErrors;
    }

    /**
     * Sets the value of the businessErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessErrors }
     *     
     */
    public void setBusinessErrors(BusinessErrors value) {
        this.businessErrors = value;
    }

}
