//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.joda.time.DateTime;


/**
 * A movement is information about an origin or
 *                 destination related to a flight
 *             
 * 
 * <p>Java class for Movement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Movement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="airport" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Airport"/>
 *         &lt;element name="city" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}City" minOccurs="0"/>
 *         &lt;element name="localDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="stopoverDuration" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Duration" minOccurs="0"/>
 *         &lt;element name="aircraftTerminal" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="passengerTerminal" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="plannedGate" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Gate" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="actualGate" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Gate" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="stand" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="runway" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="delay" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Delay" minOccurs="0"/>
 *         &lt;element name="diversionDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Movement", propOrder = {
    "sequenceNumber",
    "airport",
    "city",
    "localDateTime",
    "stopoverDuration",
    "aircraftTerminal",
    "passengerTerminal",
    "plannedGate",
    "actualGate",
    "stand",
    "runway",
    "delay",
    "diversionDateTime"
})
public class Movement {

    protected BigInteger sequenceNumber;
    @XmlElement(required = true)
    protected Airport airport;
    protected City city;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime localDateTime;
    protected Duration stopoverDuration;
    protected String aircraftTerminal;
    protected String passengerTerminal;
    protected List<Gate> plannedGate;
    protected List<Gate> actualGate;
    protected String stand;
    protected String runway;
    protected Delay delay;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime diversionDateTime;

    /**
     * Gets the value of the sequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSequenceNumber() {
        return sequenceNumber;
    }

    /**
     * Sets the value of the sequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSequenceNumber(BigInteger value) {
        this.sequenceNumber = value;
    }

    /**
     * Gets the value of the airport property.
     * 
     * @return
     *     possible object is
     *     {@link Airport }
     *     
     */
    public Airport getAirport() {
        return airport;
    }

    /**
     * Sets the value of the airport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Airport }
     *     
     */
    public void setAirport(Airport value) {
        this.airport = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link City }
     *     
     */
    public City getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link City }
     *     
     */
    public void setCity(City value) {
        this.city = value;
    }

    /**
     * Gets the value of the localDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getLocalDateTime() {
        return localDateTime;
    }

    /**
     * Sets the value of the localDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalDateTime(DateTime value) {
        this.localDateTime = value;
    }

    /**
     * Gets the value of the stopoverDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getStopoverDuration() {
        return stopoverDuration;
    }

    /**
     * Sets the value of the stopoverDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setStopoverDuration(Duration value) {
        this.stopoverDuration = value;
    }

    /**
     * Gets the value of the aircraftTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAircraftTerminal() {
        return aircraftTerminal;
    }

    /**
     * Sets the value of the aircraftTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAircraftTerminal(String value) {
        this.aircraftTerminal = value;
    }

    /**
     * Gets the value of the passengerTerminal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassengerTerminal() {
        return passengerTerminal;
    }

    /**
     * Sets the value of the passengerTerminal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassengerTerminal(String value) {
        this.passengerTerminal = value;
    }

    /**
     * Gets the value of the plannedGate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedGate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedGate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gate }
     * 
     * 
     */
    public List<Gate> getPlannedGate() {
        if (plannedGate == null) {
            plannedGate = new ArrayList<Gate>();
        }
        return this.plannedGate;
    }

    /**
     * Gets the value of the actualGate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actualGate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActualGate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Gate }
     * 
     * 
     */
    public List<Gate> getActualGate() {
        if (actualGate == null) {
            actualGate = new ArrayList<Gate>();
        }
        return this.actualGate;
    }

    /**
     * Gets the value of the stand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStand() {
        return stand;
    }

    /**
     * Sets the value of the stand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStand(String value) {
        this.stand = value;
    }

    /**
     * Gets the value of the runway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRunway() {
        return runway;
    }

    /**
     * Sets the value of the runway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRunway(String value) {
        this.runway = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link Delay }
     *     
     */
    public Delay getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link Delay }
     *     
     */
    public void setDelay(Delay value) {
        this.delay = value;
    }

    /**
     * Gets the value of the diversionDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getDiversionDateTime() {
        return diversionDateTime;
    }

    /**
     * Sets the value of the diversionDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDiversionDateTime(DateTime value) {
        this.diversionDateTime = value;
    }

}
