//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationalDepartureStatusCodeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationalDepartureStatusCodeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SCH"/>
 *     &lt;enumeration value="OFB"/>
 *     &lt;enumeration value="GRT"/>
 *     &lt;enumeration value="DX"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OperationalDepartureStatusCodeEnum")
@XmlEnum
public enum OperationalDepartureStatusCodeEnum {

    SCH,
    OFB,
    GRT,
    DX;

    public String value() {
        return name();
    }

    public static OperationalDepartureStatusCodeEnum fromValue(String v) {
        return valueOf(v);
    }

}
