//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Event occurring as part of the process of
 *                 operating
 *                 flights.
 *             
 * 
 * <p>Java class for OperationalEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationalEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}OperationalEventEnum"/>
 *         &lt;element name="actualDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="calculatedDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="targettedDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="ScheduledDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="plannedDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="estimatedDateTime" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}EventDate" minOccurs="0"/>
 *         &lt;element name="location" type="{http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01}Location" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationalEvent", propOrder = {
    "type",
    "actualDateTime",
    "calculatedDateTime",
    "targettedDateTime",
    "scheduledDateTime",
    "plannedDateTime",
    "estimatedDateTime",
    "location"
})
public class OperationalEvent {

    @XmlElement(required = true)
    protected OperationalEventEnum type;
    protected EventDate actualDateTime;
    protected EventDate calculatedDateTime;
    protected EventDate targettedDateTime;
    @XmlElement(name = "ScheduledDateTime")
    protected EventDate scheduledDateTime;
    protected EventDate plannedDateTime;
    protected EventDate estimatedDateTime;
    protected Location location;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link OperationalEventEnum }
     *     
     */
    public OperationalEventEnum getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationalEventEnum }
     *     
     */
    public void setType(OperationalEventEnum value) {
        this.type = value;
    }

    /**
     * Gets the value of the actualDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getActualDateTime() {
        return actualDateTime;
    }

    /**
     * Sets the value of the actualDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setActualDateTime(EventDate value) {
        this.actualDateTime = value;
    }

    /**
     * Gets the value of the calculatedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getCalculatedDateTime() {
        return calculatedDateTime;
    }

    /**
     * Sets the value of the calculatedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setCalculatedDateTime(EventDate value) {
        this.calculatedDateTime = value;
    }

    /**
     * Gets the value of the targettedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getTargettedDateTime() {
        return targettedDateTime;
    }

    /**
     * Sets the value of the targettedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setTargettedDateTime(EventDate value) {
        this.targettedDateTime = value;
    }

    /**
     * Gets the value of the scheduledDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getScheduledDateTime() {
        return scheduledDateTime;
    }

    /**
     * Sets the value of the scheduledDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setScheduledDateTime(EventDate value) {
        this.scheduledDateTime = value;
    }

    /**
     * Gets the value of the plannedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getPlannedDateTime() {
        return plannedDateTime;
    }

    /**
     * Sets the value of the plannedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setPlannedDateTime(EventDate value) {
        this.plannedDateTime = value;
    }

    /**
     * Gets the value of the estimatedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link EventDate }
     *     
     */
    public EventDate getEstimatedDateTime() {
        return estimatedDateTime;
    }

    /**
     * Sets the value of the estimatedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDate }
     *     
     */
    public void setEstimatedDateTime(EventDate value) {
        this.estimatedDateTime = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link Location }
     *     
     */
    public Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link Location }
     *     
     */
    public void setLocation(Location value) {
        this.location = value;
    }

}
