//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ba.com/schema/fdm/FlightManagerV02/GetAircraftLinkedFlightsResponseV01")
package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;
