//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.30 at 01:53:08 PM BST 
//


package com.xxx.schema.fdm.flightmanagerv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for publicArrivalStatusEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="publicArrivalStatusEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ON_TIME"/>
 *     &lt;enumeration value="CANCELLED"/>
 *     &lt;enumeration value="REROUTED"/>
 *     &lt;enumeration value="NIGHT_STOPPED"/>
 *     &lt;enumeration value="DELAYED"/>
 *     &lt;enumeration value="DIVERTED"/>
 *     &lt;enumeration value="ARRIVED"/>
 *     &lt;enumeration value="ARRIVED_EARLY"/>
 *     &lt;enumeration value="ARRIVED_LATE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "publicArrivalStatusEnum")
@XmlEnum
public enum PublicArrivalStatusEnum {

    ON_TIME,
    CANCELLED,
    REROUTED,
    NIGHT_STOPPED,
    DELAYED,
    DIVERTED,
    ARRIVED,
    ARRIVED_EARLY,
    ARRIVED_LATE;

    public String value() {
        return name();
    }

    public static PublicArrivalStatusEnum fromValue(String v) {
        return valueOf(v);
    }

}
