//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 10:07:40 AM BST 
//


package com.xxx.schema.pega.pegasusadapterv02.getaircraftlinkedflightsresponsev01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Encapsulates a measured number of units of time
 *                 e.g. 55 minutes. A minus sign may optionally be used to prefix
 *                 the
 *                 measurement number. This provides requisite flexibility in
 *                 situations where durations are stored relative to a specific
 *                 time
 *                 e.g. -55 minutes meaning before that time.
 *             
 * 
 * <p>Java class for Duration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Duration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="measure">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;minInclusive value="-9999"/>
 *               &lt;maxInclusive value="9999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="unitOfTime" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}UnitOfTimeEnum"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Duration", propOrder = {
    "measure",
    "unitOfTime"
})
public class Duration {

    protected int measure;
    @XmlElement(required = true)
    protected UnitOfTimeEnum unitOfTime;

    /**
     * Gets the value of the measure property.
     * 
     */
    public int getMeasure() {
        return measure;
    }

    /**
     * Sets the value of the measure property.
     * 
     */
    public void setMeasure(int value) {
        this.measure = value;
    }

    /**
     * Gets the value of the unitOfTime property.
     * 
     * @return
     *     possible object is
     *     {@link UnitOfTimeEnum }
     *     
     */
    public UnitOfTimeEnum getUnitOfTime() {
        return unitOfTime;
    }

    /**
     * Sets the value of the unitOfTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitOfTimeEnum }
     *     
     */
    public void setUnitOfTime(UnitOfTimeEnum value) {
        this.unitOfTime = value;
    }

}
