//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.03 at 10:07:40 AM BST 
//


package com.xxx.schema.pega.pegasusadapterv02.getaircraftlinkedflightsresponsev01;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.joda.time.DateTime;


/**
 * A flight leg is a journey made by an aircraft A
 *                 Flight Leg is not marketed, so the only flight number available
 *                 to
 *                 it is the operating one.
 *             
 * 
 * <p>Java class for FlightLeg complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightLeg">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="repeatNumber" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="currentOrigin" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}Movement"/>
 *         &lt;element name="currentDestination" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}Movement"/>
 *         &lt;element name="legTimings" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}FlightTimings"/>
 *         &lt;element name="aircraftForFlightLeg" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}AircraftForFlightLeg" minOccurs="0"/>
 *         &lt;element name="legDuration" type="{http://www.ba.com/schema/pega/PegasusAdapterV02/GetAircraftLinkedFlightsResponseV01}Duration" minOccurs="0"/>
 *         &lt;element name="updateDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightLeg", propOrder = {
    "repeatNumber",
    "currentOrigin",
    "currentDestination",
    "legTimings",
    "aircraftForFlightLeg",
    "legDuration",
    "updateDateTime"
})
public class FlightLeg {

    @XmlElement(required = true)
    protected BigInteger repeatNumber;
    @XmlElement(required = true)
    protected Movement currentOrigin;
    @XmlElement(required = true)
    protected Movement currentDestination;
    @XmlElement(required = true)
    protected FlightTimings legTimings;
    protected AircraftForFlightLeg aircraftForFlightLeg;
    protected Duration legDuration;
    @XmlElement(type = String.class)
    @XmlSchemaType(name = "dateTime")
    protected DateTime updateDateTime;

    /**
     * Gets the value of the repeatNumber property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRepeatNumber() {
        return repeatNumber;
    }

    /**
     * Sets the value of the repeatNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRepeatNumber(BigInteger value) {
        this.repeatNumber = value;
    }

    /**
     * Gets the value of the currentOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link Movement }
     *     
     */
    public Movement getCurrentOrigin() {
        return currentOrigin;
    }

    /**
     * Sets the value of the currentOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movement }
     *     
     */
    public void setCurrentOrigin(Movement value) {
        this.currentOrigin = value;
    }

    /**
     * Gets the value of the currentDestination property.
     * 
     * @return
     *     possible object is
     *     {@link Movement }
     *     
     */
    public Movement getCurrentDestination() {
        return currentDestination;
    }

    /**
     * Sets the value of the currentDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Movement }
     *     
     */
    public void setCurrentDestination(Movement value) {
        this.currentDestination = value;
    }

    /**
     * Gets the value of the legTimings property.
     * 
     * @return
     *     possible object is
     *     {@link FlightTimings }
     *     
     */
    public FlightTimings getLegTimings() {
        return legTimings;
    }

    /**
     * Sets the value of the legTimings property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightTimings }
     *     
     */
    public void setLegTimings(FlightTimings value) {
        this.legTimings = value;
    }

    /**
     * Gets the value of the aircraftForFlightLeg property.
     * 
     * @return
     *     possible object is
     *     {@link AircraftForFlightLeg }
     *     
     */
    public AircraftForFlightLeg getAircraftForFlightLeg() {
        return aircraftForFlightLeg;
    }

    /**
     * Sets the value of the aircraftForFlightLeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link AircraftForFlightLeg }
     *     
     */
    public void setAircraftForFlightLeg(AircraftForFlightLeg value) {
        this.aircraftForFlightLeg = value;
    }

    /**
     * Gets the value of the legDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getLegDuration() {
        return legDuration;
    }

    /**
     * Sets the value of the legDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setLegDuration(Duration value) {
        this.legDuration = value;
    }

    /**
     * Gets the value of the updateDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public DateTime getUpdateDateTime() {
        return updateDateTime;
    }

    /**
     * Sets the value of the updateDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUpdateDateTime(DateTime value) {
        this.updateDateTime = value;
    }

}
